checking for valgrind

diff --git a/check_requirements b/check_requirements
--- a/check_requirements
+++ b/check_requirements
@@ -36,6 +36,12 @@ then
     ecode=1
 fi
 
+if ! command -v valgrind &> /dev/null
+then
+    echo "valgrind: could not be found"
+    ecode=1
+fi
+
 
 if [ "$ecode" == 0 ]
 then
