fix: removed unwanted files, added check for moss

diff --git a/src/check_requirements b/src/check_requirements
--- a/src/check_requirements
+++ b/src/check_requirements
@@ -62,9 +62,11 @@ then
     ecode=1
 fi
 
-if [ "$ecode" == 0 ]
+if ! command -v ./moss &> /dev/null
 then
-    exit 0
-else
-    exit 1
+    echo "command moss: could not be found.
+Details on how to obtain MOSS can be found here: https://theory.stanford.edu/~aiken/moss/"
+    ecode=1
 fi
+
+exit $ecode
